# <center><strong>PROBLEM SET 2</strong></center>
### <center>Milton Straw --- ECON 815: Topics in Microeconomics --- Fall 2019</center>

## 1. The Standard Library

## 1.1

In [2]:
# Creating List
L = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(L)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [6]:
# Defining average
def mean(L):
    return sum(L) / len(L)

In [16]:
print("Minimum of the list =", min(L), ", Maximum =", max(L), ", and Average =", mean(L))

Minimum of the list = 1 , Maximum = 10 , and Average = 5.5


## 1.2

In [77]:
# Integer
int_1 = 1
int_2 = int_1
int_2 = int_2 + 1
int_1 == int_2

False

In [38]:
# String
mydog = 'Magnolia'
nickname = mydog
nickname = 'Nolah'
mydog == nickname

False

In [46]:
# List
groceries = ['milk', 'bread', 'meat', 'fruit', 'vegetables']
shopping = groceries
shopping[4] = 'candy'
groceries == shopping

True

In [81]:
# Tuple -- adding an item to the list
my_tuple_3 = (5, 10, 20, 'm', 'a', 's')
my_tuple_4 = my_tuple_3
my_tuple_4 += (1,)
my_tuple_3 == my_tuple_4

False

In [5]:
# Set
set_1 = {3, 2, 1, 'x', 'y', 'z'}
set_2 = set_1
set_2 = {1, 2, 5, 'x', 'y', 'z'}
set_1 == set_2

False

## 1.3

In [70]:
import calculator as calc

In [71]:
# Triangle
a = 10
b = 6

In [72]:
run calculator

In [86]:
# Hypotenuse -- a**2 + b**2 = c**2
c = sqrt(calc.sum_of_arguments(calc.product_of_arguments(a, a), calc.product_of_arguments(b, b)))
print(c)

11.661903789690601


## 2.1

In [3]:
import numpy as np

In [5]:
A = np.array([[3, -1, 4], [1, 5, 9]])
print(A)

[[ 3 -1  4]
 [ 1  5  9]]


In [6]:
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
print(B)

[[ 2  6 -5  3]
 [ 5 -8  9  7]
 [ 9 -3 -2 -3]]


In [7]:
np.dot(A, B)

array([[ 37,  14, -32, -10],
       [108, -61,  22,  11]])

## 2.2

In [94]:
A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
print(A)

[[ 3  1  4]
 [ 1  5  9]
 [-5  3  1]]


In [98]:
def afunction():
    
    return -(A @ A @ A) + (9 * (A @ A)) - (15 * A)
afunction()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 2.5

In [34]:
A = np.array([[0, 2, 4], [1, 3, 5]])
B = np.array([[3, 0, 0], [3, 3, 0], [3, 3, 3]])
C = np.array([[-2, 0, 0], [0, -2, 0], [0, 0, -2]])
print(A)
print(B)
print(C)

[[0 2 4]
 [1 3 5]]
[[3 0 0]
 [3 3 0]
 [3 3 3]]
[[-2  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [54]:
# np.vstack((np.zeros((3, 3)), A, B))
# np.vstack((A.T, np.zeros((2, 2)), np.zeros((3, 2))))
# np.vstack((np.eye(3), np.zeros((2, 3)), C))
r1 = np.column_stack((np.zeros((3, 3)), A.T, np.eye(3)))
r2 = np.column_stack((A, np.zeros((2, 2)), np.zeros((2, 3))))
r3 = np.column_stack((B, np.zeros((3, 2)), C))
block_matrix = np.concatenate((r1, r2, r3))
print(block_matrix)

[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


## 3.1

In [113]:
class Backpack:
    """
    A Backpack object class. Has a name and a list of contents.
    Attributes:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the max number of items the backpack can hold.
        contents (list): the contents of the backpack.
    """
    def __init__(self, name, color, max_size = 5):           # This function is the constructor.
        """Set the name and initialize an empty list of contents.
        Parameters:
            name (str): the name of the backpack's owner.
        """
        self.name = name                # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents = []
        
    def put(self, item):
        """
        Add 'item' to the backpack's list of contents.
        
        Args:
            item (str): name of the item being put in the backpack.
            
        Returns: 
            contents (list): list of items in the backpack after the addition.
        """
        if len(self.contents) < 5:
            self.contents.append(item)
        else:
            print("No Rooms!")
            
    def dump(self):
        '''
        Empties all contents of the backpack.
        
        Args:
            ...:
            
        Returns:
            contents (list): an empty list, after all of the items have been removed from the backpack.
        '''
        self.contents = []

In [115]:
def test_backpack():
    testpack = Backpack("Milton", "tan")       # Instantiate the object.
    if testpack.name != "Milton":                # Test an attribute.
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "notebook", "iPad"]:
        testpack.put(item)                      # Test a method.
    print("Contents:", testpack.contents)
test_backpack()

Contents: ['pencil', 'pen', 'notebook', 'iPad']


## 3.2

In [119]:
class Jetpack(Backpack):
    '''
    A Jetpack is a subclass of a Backpack. It has an additional attribute.
    Attributes:
        name (str): the name of the jetpack's owner.
        color (str): the color of the jetpack.
        max_size (int): the max number of items the jetpack can hold.
        fuel (int): the amount of fuel in the jetpack.
        contents (list): the contents of the jetpack.
    '''
    def __init__(self, name, color, max_size = 2):            # Override the constructor.
        """
        Change the max_size of the jetpack and add a fuel atrtibute.
        """
        
        Backpack.__init__(self, name, color, max_size)
        self.fuel = 10
        
    def fly(self, burn):
        '''
        Choose how much fuel to burn when flying.
        
        Args:
            burn: the amount of fuel to burn when flying.
        
        Returns:
            fuel: if there current level of fuel is at least as large as the chosen amount to burn,
            then fly() will be successful and the remaining fuel after the flight will be returned.
            If there is not enough fuel in the jetpack for the amount chosen in fly(), it will print
            a message stating that there is "Not enoufh fuel!" and the flight will not occur.
        '''
        if burn > self.fuel:
            print("Not enough fuel!")
        else:
            self.fuel = self.fuel - burn
            
    def dump(self):
        '''
        Empties all contents and fuel of the jetpack.
        
        Args:
            ...:
            
        Returns:
            contents: All of the contents and fuel will be removed from the jetpack. It will
            return an empty list and set the fuel amount to zero.
        '''
        self.contents = []
        self.fuel = 0

In [120]:
def test_jetpack():
    testjet = Jetpack("Milton", "chrome")       # Instantiate the object.
    testjet.fly(5)                      # Test flight!
    print("Fuel Remaining:", testjet.fuel)
test_jetpack()

Fuel Remaining: 5
